# traefik.yml

# ...
# other configurations
# ...

entryPoints:
  web:
    address: ":80"

providers:
  docker:
    exposedByDefault: false
    network: traefik
    endpoint: "tcp://dockerproxy:2375"

# ...
# other configurations
# ...